// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":false,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"TitleCommandPosition","status":true,"description":"Changes the position of the title command window.","parameters":{"Offset X":"-200","Offset Y":"0","Width":"200","Background":"2"}},
{"name":"FTKR_DeleteSavefile","status":true,"description":"v1.0.4 新增刪除指令來移除存檔","parameters":{"--コマンド名--":"","Save Command Name":"保存","Load Command Name":"讀取","Delete Command Name":"刪除","--セーブファイル削除SE--":"","Delete File Se":"","--削除確認--":"","Enable Confirmation":"true","Conf Title Format":"要刪除 %1%2 嗎？","Confirmation Ok Format":"是","Confirmation Cancel Format":"否","Enable Conf Window Setting":"false","Conf Window Setting":""}},
{"name":"AltMenuScreen3","status":true,"description":"更改選單畫面排版。(ver1.0.1)","parameters":{"bgBitmapMenu":"S__83550244","bgBitmapItem":"S__83550244","bgBitmapSkill":"S__83550244","bgBitmapEquip":"S__83550244","bgBitmapStatus":"S__83550244","bgBitmapOptions":"","bgBitmapFile":"","bgBitmapGameEnd":"","maxColsMenu":"4","commandRows":"2","isDisplayStatus":"0","display map name":"1","location string":"所在地 :"}}
];
